"""Add reviewed_by_id to Request

Revision ID: 1436f00a5fff
Revises: 96a50b0498d8
Create Date: 2025-02-20 01:25:21.131428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1436f00a5fff'
down_revision = '96a50b0498d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'),
               nullable=False)
        batch_op.alter_column('urgency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
