"""Reinitializing migrations

Revision ID: 33217cc97ad6
Revises: 
Create Date: 2025-02-19 23:01:52.090117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33217cc97ad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))  # Allow NULL initially

    # Manually update existing rows to have a default value
    op.execute("UPDATE asset SET name = 'Unnamed Asset' WHERE name IS NULL")

    # Now enforce NOT NULL constraint
    op.alter_column('asset', 'name', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('asset_allocated_to_fkey', 'user', ['allocated_to'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
