"""add

Revision ID: 3c93df448c57
Revises: 0f5a1b5898b4
Create Date: 2025-02-21 10:47:43.990973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c93df448c57'
down_revision = '0f5a1b5898b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_name')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'),
               type_=sa.String(length=20),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_username', ['username'], unique=True)
        batch_op.create_index('ix_user_email', ['email'], unique=True)

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'),
               nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_name', ['name'], unique=True)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index('ix_asset_name', ['name'], unique=False)

    # ### end Alembic commands ###
