"""Updated user and request models

Revision ID: 59dc6084a10e
Revises: 4130b97094a4
Create Date: 2025-02-19 09:59:22.342925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dc6084a10e'
down_revision = '4130b97094a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('request_reviewed_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewed_by_id'], ['id'])
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('request_reviewed_by_fkey', 'user', ['reviewed_by'], ['id'])
        batch_op.drop_column('reviewed_by_id')

    # ### end Alembic commands ###
