"""Add reset_token to User

Revision ID: 97656506ab39
Revises: 3c93df448c57
Create Date: 2025-02-21 15:37:35.367036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97656506ab39'
down_revision = '3c93df448c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
